// _lib.js — shared logic for the /supply/* Cloudflare Pages Functions on the
// bankcoin-assets project (assets.bankcoin.capital).
//
// MONEY-TRUTH RULE (CLAUDE.md): never return a fabricated or stale-silent
// number. Every figure served here is a live, block-pinned chain read.
// On RPC failure we return HTTP 503 — never 200-with-garbage. Successful
// responses are edge-cached for 60 seconds (freshness bound is explicit in
// the Cache-Control header and in /supply/meta's asOfBlock).
//
// Data source of record for token + exclusion addresses:
//   /supply/exclusions.json — generated by scripts/publish_token_assets.sh
//   from .credentials/cpp/contracts.env and validated on-chain at publish
//   time. The functions NEVER hardcode addresses.
//
// Circulating-supply policy (docs/INSTITUTIONAL_ACCEPTANCE.md §E — "NEVER
// overstate. When in doubt, exclude."):
//   circulating = totalSupply() − Σ balanceOf(excluded addresses)
// at a single pinned block. The per-family exclusion semantics are carried
// in the config's `policy` object and echoed by /supply/meta.

export const CACHE_SECONDS = 60;

const CORS_HEADERS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, OPTIONS",
  "Access-Control-Allow-Headers": "*",
};

const SEL_TOTAL_SUPPLY = "0x18160ddd"; // totalSupply()
const SEL_BALANCE_OF = "0x70a08231"; // balanceOf(address)

// ---------------------------------------------------------------------------
// Responses
// ---------------------------------------------------------------------------

export function corsPreflight() {
  return new Response(null, { status: 204, headers: CORS_HEADERS });
}

export function textResponse(body, status = 200, cacheable = status === 200) {
  return new Response(body, {
    status,
    headers: {
      ...CORS_HEADERS,
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": cacheable
        ? `public, max-age=${CACHE_SECONDS}`
        : "no-store",
      ...(status === 503 ? { "Retry-After": "10" } : {}),
    },
  });
}

export function jsonResponse(obj, status = 200, cacheable = status === 200) {
  return new Response(JSON.stringify(obj, null, 2) + "\n", {
    status,
    headers: {
      ...CORS_HEADERS,
      "Content-Type": "application/json; charset=utf-8",
      "Cache-Control": cacheable
        ? `public, max-age=${CACHE_SECONDS}`
        : "no-store",
      ...(status === 503 ? { "Retry-After": "10" } : {}),
    },
  });
}

// A typed error carrying the HTTP status we should surface.
export class SupplyError extends Error {
  constructor(status, message) {
    super(message);
    this.status = status;
  }
}

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------

export async function loadConfig(context) {
  const url = new URL("/supply/exclusions.json", context.request.url);
  const res = await context.env.ASSETS.fetch(new Request(url.toString()));
  if (!res.ok) {
    throw new SupplyError(
      503,
      "supply configuration (exclusions.json) unavailable"
    );
  }
  return await res.json();
}

// Resolve ?symbol=&chainId= against the config. Symbol match is
// case-insensitive; the canonical casing from the config is used thereafter.
export function resolveToken(config, symbolParam, chainIdParam) {
  if (!symbolParam || !chainIdParam) {
    throw new SupplyError(400, "required query params: symbol, chainId");
  }
  if (!/^[0-9]+$/.test(chainIdParam)) {
    throw new SupplyError(400, `chainId must be a decimal integer`);
  }
  const chain = config.chains[chainIdParam];
  if (!chain) {
    throw new SupplyError(
      404,
      `unknown chainId ${chainIdParam}; supported: ${Object.keys(
        config.chains
      ).join(", ")}`
    );
  }
  const wanted = symbolParam.toLowerCase();
  const symbol = Object.keys(chain.tokens).find(
    (s) => s.toLowerCase() === wanted
  );
  if (!symbol) {
    throw new SupplyError(
      404,
      `unknown symbol ${symbolParam} on chainId ${chainIdParam}`
    );
  }
  return { chainId: chainIdParam, chain, symbol, token: chain.tokens[symbol] };
}

// ---------------------------------------------------------------------------
// JSON-RPC (batch, block-pinned, multi-endpoint failover)
// ---------------------------------------------------------------------------

export async function rpcPost(rpcUrl, payload) {
  const res = await fetch(rpcUrl, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(payload),
    signal: AbortSignal.timeout(10_000),
  });
  if (!res.ok) throw new Error(`${rpcUrl} -> HTTP ${res.status}`);
  return await res.json();
}

function hexToBigInt(hex, what) {
  if (typeof hex !== "string" || !/^0x[0-9a-fA-F]*$/.test(hex)) {
    throw new Error(`malformed hex result for ${what}: ${hex}`);
  }
  return BigInt(hex === "0x" ? "0x0" : hex);
}

// ---------------------------------------------------------------------------
// Multicall3 path (preferred): every read collapses into ONE eth_call at the
// pinned block — a single consistent state root, and it stays inside public-
// RPC rate limits (mainnet.base.org caps batches at 10 calls AND rate-limits
// sequential chunks; verified 2026-07-07: -32014 / -32016). Multicall3 is the
// canonical deterministic deployment, verified on Base/Arbitrum/Ethereum.
// ---------------------------------------------------------------------------

const SEL_AGGREGATE = "0x252dba42"; // aggregate((address,bytes)[]) -> (uint256,bytes[])

export function pad32(hex) {
  return hex.replace(/^0x/, "").padStart(64, "0");
}

// ABI-encode Multicall3.aggregate(Call[] calls) calldata where each call is
// (address target, bytes callData). Reverts if any inner call reverts — which
// is what we want: a failed read must fail the response (503), never zero-fill.
export function encodeAggregate(calls) {
  const words = [];
  words.push(pad32("0x20")); // offset to Call[]
  words.push(pad32("0x" + calls.length.toString(16))); // array length
  // element offsets, relative to the first byte after the length word
  const elems = calls.map(({ target, data }) => {
    const d = data.replace(/^0x/, "");
    const lenBytes = d.length / 2;
    const padded = d.padEnd(Math.ceil(lenBytes / 32) * 64, "0");
    return (
      pad32(target) + // word0: target address
      pad32("0x40") + // word1: offset to bytes within the tuple
      pad32("0x" + lenBytes.toString(16)) + // word2: bytes length
      padded // word3+: data, right-padded
    );
  });
  let offset = calls.length * 32; // offsets table itself
  for (const e of elems) {
    words.push(pad32("0x" + offset.toString(16)));
    offset += e.length / 2;
  }
  return SEL_AGGREGATE + words.join("") + elems.join("");
}

// Decode aggregate's (uint256 blockNumber, bytes[] returnData) where every
// inner return is a single uint256 (totalSupply / balanceOf).
function decodeAggregateUints(hex, expectedCount) {
  const h = hex.replace(/^0x/, "");
  const word = (i) => h.slice(i * 64, (i + 1) * 64);
  if (h.length < 4 * 64) throw new Error(`aggregate return too short: ${hex.slice(0, 66)}`);
  const arrOffset = Number(BigInt("0x" + word(1))) / 32; // words to bytes[] head
  const n = Number(BigInt("0x" + word(arrOffset)));
  if (n !== expectedCount) {
    throw new Error(`aggregate returned ${n} results, expected ${expectedCount}`);
  }
  const values = [];
  for (let i = 0; i < n; i++) {
    const elemOffsetWords = Number(BigInt("0x" + word(arrOffset + 1 + i))) / 32;
    const elemBase = arrOffset + 1 + elemOffsetWords;
    const len = Number(BigInt("0x" + word(elemBase)));
    if (len !== 32) throw new Error(`inner return ${i} length ${len}, expected 32`);
    values.push(BigInt("0x" + word(elemBase + 1)));
  }
  return values;
}

async function readSupplyViaMulticall(rpcUrl, multicall3, tokenAddress, exclusionAddresses) {
  const bnRes = await rpcPost(rpcUrl, {
    jsonrpc: "2.0",
    id: 0,
    method: "eth_blockNumber",
    params: [],
  });
  if (bnRes.error || !bnRes.result) {
    throw new Error(`${rpcUrl} eth_blockNumber: ${JSON.stringify(bnRes.error)}`);
  }
  const blockHex = bnRes.result;

  const calls = [
    { target: tokenAddress, data: SEL_TOTAL_SUPPLY },
    ...exclusionAddresses.map((addr) => ({
      target: tokenAddress,
      data: SEL_BALANCE_OF + pad32(addr),
    })),
  ];
  const res = await rpcPost(rpcUrl, {
    jsonrpc: "2.0",
    id: 1,
    method: "eth_call",
    params: [{ to: multicall3, data: encodeAggregate(calls) }, blockHex],
  });
  if (res.error || !res.result) {
    throw new Error(`${rpcUrl} multicall aggregate: ${JSON.stringify(res.error)}`);
  }
  const values = decodeAggregateUints(res.result, calls.length);
  return {
    blockNumber: Number(hexToBigInt(blockHex, "blockNumber")),
    totalSupply: values[0],
    balances: values.slice(1),
    rpcUrl,
  };
}

// ---------------------------------------------------------------------------
// Raw batch fallback (for a chain whose config carries no multicall3 address).
// Public RPC batch caps vary (mainnet.base.org rejects >10 calls per batch,
// verified 2026-07-07: error -32014 "maximum 10 calls in 1 batch"). Chunk to
// the lowest common cap; every chunk stays pinned to the SAME block so the
// numbers within one response remain a single consistent state.
// ---------------------------------------------------------------------------

const MAX_BATCH_CALLS = 10;

// Reads, against ONE rpc endpoint, at ONE pinned block:
//   totalSupply(token) and balanceOf(token, addr) for every exclusion addr.
async function readSupplyAtRpc(rpcUrl, tokenAddress, exclusionAddresses) {
  const bnRes = await rpcPost(rpcUrl, {
    jsonrpc: "2.0",
    id: 0,
    method: "eth_blockNumber",
    params: [],
  });
  if (bnRes.error || !bnRes.result) {
    throw new Error(`${rpcUrl} eth_blockNumber: ${JSON.stringify(bnRes.error)}`);
  }
  const blockHex = bnRes.result;

  const calls = [
    {
      jsonrpc: "2.0",
      id: 1,
      method: "eth_call",
      params: [{ to: tokenAddress, data: SEL_TOTAL_SUPPLY }, blockHex],
    },
    ...exclusionAddresses.map((addr, i) => ({
      jsonrpc: "2.0",
      id: 2 + i,
      method: "eth_call",
      params: [
        {
          to: tokenAddress,
          data:
            SEL_BALANCE_OF + addr.toLowerCase().replace(/^0x/, "").padStart(64, "0"),
        },
        blockHex,
      ],
    })),
  ];

  const results = [];
  for (let i = 0; i < calls.length; i += MAX_BATCH_CALLS) {
    const chunk = calls.slice(i, i + MAX_BATCH_CALLS);
    const chunkRes = await rpcPost(rpcUrl, chunk);
    if (!Array.isArray(chunkRes) || chunkRes.length !== chunk.length) {
      throw new Error(
        `${rpcUrl}: batch response shape mismatch (${JSON.stringify(
          chunkRes
        ).slice(0, 200)})`
      );
    }
    results.push(...chunkRes);
  }
  const byId = new Map(results.map((r) => [r.id, r]));
  const get = (id, what) => {
    const r = byId.get(id);
    if (!r || r.error) {
      throw new Error(`${rpcUrl} ${what}: ${JSON.stringify(r && r.error)}`);
    }
    return hexToBigInt(r.result, what);
  };

  const totalSupply = get(1, "totalSupply");
  const balances = exclusionAddresses.map((addr, i) =>
    get(2 + i, `balanceOf(${addr})`)
  );
  return { blockNumber: Number(hexToBigInt(blockHex, "blockNumber")), totalSupply, balances, rpcUrl };
}

// Try each configured RPC in order; each endpoint pins its own fresh block so
// all numbers within one response are from a single consistent state. Chains
// with a multicall3 address in config use the single-eth_call path; others
// fall back to chunked JSON-RPC batches.
export async function readSupply(chain, token) {
  const exclusionAddresses = (chain.exclusions || []).map((e) => e.address);
  const errors = [];
  for (const rpcUrl of chain.rpcs) {
    try {
      if (chain.multicall3) {
        return await readSupplyViaMulticall(
          rpcUrl,
          chain.multicall3,
          token.address,
          exclusionAddresses
        );
      }
      return await readSupplyAtRpc(rpcUrl, token.address, exclusionAddresses);
    } catch (e) {
      errors.push(String(e && e.message ? e.message : e));
    }
  }
  throw new SupplyError(
    503,
    `all RPC endpoints failed for chain: ${errors.join(" | ")}`
  );
}

// ---------------------------------------------------------------------------
// Exact decimal formatting (BigInt only — no floats, per CLAUDE.md)
// ---------------------------------------------------------------------------

export function formatUnits(value, decimals) {
  const neg = value < 0n;
  const abs = neg ? -value : value;
  const base = 10n ** BigInt(decimals);
  const intPart = (abs / base).toString();
  const fracPart = (abs % base)
    .toString()
    .padStart(decimals, "0")
    .replace(/0+$/, "");
  return (neg ? "-" : "") + intPart + (fracPart ? "." + fracPart : "");
}

// ---------------------------------------------------------------------------
// Core computation shared by all three endpoints
// ---------------------------------------------------------------------------

// Cross-chain AGGREGATE: when chainId is omitted, sum totalSupply and
// circulating across EVERY configured chain that carries the symbol. This is
// what CoinGecko/CMC display for a multi-chain token (kUSD lives on Base +
// Arbitrum). Same accuracy discipline: any per-chain RPC failure throws (no
// partial/stale aggregate). Decimals are uniform across the kStable family (6);
// asserted per chain.
export async function computeSupplyAggregate(context) {
  const config = await loadConfig(context);
  const url = new URL(context.request.url);
  const symbolParam = url.searchParams.get("symbol");
  if (!symbolParam) throw new SupplyError(400, "required query param: symbol");
  const wanted = symbolParam.toLowerCase();

  let totalSupply = 0n;
  let circulating = 0n;
  let decimals = null;
  const perChain = [];
  for (const chainId of Object.keys(config.chains)) {
    const chain = config.chains[chainId];
    const symbol = Object.keys(chain.tokens).find(
      (s) => s.toLowerCase() === wanted
    );
    if (!symbol) continue;
    const token = chain.tokens[symbol];
    if (decimals === null) decimals = token.decimals;
    else if (decimals !== token.decimals) {
      throw new SupplyError(
        500,
        `decimals mismatch across chains for ${symbol}: ${decimals} vs ${token.decimals}`
      );
    }
    const { blockNumber, totalSupply: ts, balances } = await readSupply(chain, token);
    let excluded = 0n;
    (chain.exclusions || []).forEach((_e, i) => (excluded += balances[i]));
    const circ = ts - excluded;
    if (circ < 0n) {
      throw new SupplyError(
        500,
        `invariant violation on ${symbol}@${chainId}: excluded > totalSupply`
      );
    }
    totalSupply += ts;
    circulating += circ;
    perChain.push({ chainId: Number(chainId), asOfBlock: blockNumber });
  }
  if (decimals === null) {
    throw new SupplyError(404, `unknown symbol ${symbolParam} on any chain`);
  }
  return {
    symbol: symbolParam,
    aggregate: true,
    chains: perChain,
    totalSupply: totalSupply.toString(),
    totalSupplyFormatted: formatUnits(totalSupply, decimals),
    circulating: circulating.toString(),
    circulatingFormatted: formatUnits(circulating, decimals),
  };
}

export async function computeSupply(context) {
  const url = new URL(context.request.url);
  const config = await loadConfig(context);
  const { chainId, chain, symbol, token } = resolveToken(
    config,
    url.searchParams.get("symbol"),
    url.searchParams.get("chainId")
  );

  const { blockNumber, totalSupply, balances, rpcUrl } = await readSupply(
    chain,
    token
  );

  let excludedTotal = 0n;
  const exclusions = (chain.exclusions || []).map((e, i) => {
    excludedTotal += balances[i];
    return {
      label: e.label,
      address: e.address,
      balance: balances[i].toString(),
      balanceFormatted: formatUnits(balances[i], token.decimals),
    };
  });

  const circulating = totalSupply - excludedTotal;
  if (circulating < 0n) {
    // Exclusion balances exceeding totalSupply is an accounting-invariant
    // violation (double-counted exclusion or wrong token address). Surface
    // loudly; never publish a clamped or negative figure.
    throw new SupplyError(
      500,
      `invariant violation: excluded ${excludedTotal} > totalSupply ${totalSupply} for ${symbol}@${chainId}`
    );
  }

  return {
    symbol,
    chainId: Number(chainId),
    tokenAddress: token.address,
    decimals: token.decimals,
    asOfBlock: blockNumber,
    totalSupply: totalSupply.toString(),
    totalSupplyFormatted: formatUnits(totalSupply, token.decimals),
    circulating: circulating.toString(),
    circulatingFormatted: formatUnits(circulating, token.decimals),
    excludedTotal: excludedTotal.toString(),
    excludedTotalFormatted: formatUnits(excludedTotal, token.decimals),
    exclusions,
    policy: config.policy || {},
    chainNotes: chain.notes || undefined,
    source: {
      rpc: rpcUrl,
      config: "/supply/exclusions.json",
      configVersion: config.version,
      configGeneratedAtUtc: config.generatedAtUtc,
    },
  };
}

// ---------------------------------------------------------------------------
// 60s edge cache (Cache API). Only 200s are cached; errors are never cached.
// ---------------------------------------------------------------------------

export async function withEdgeCache(context, handler) {
  const url = new URL(context.request.url);
  // Normalised cache key: path + canonical param order (case-normalised
  // symbol) so kusd/kUSD and reordered params share one cache entry.
  const key = new Request(
    `${url.origin}${url.pathname}?symbol=${(
      url.searchParams.get("symbol") || ""
    ).toLowerCase()}&chainId=${url.searchParams.get("chainId") || ""}`,
    { method: "GET" }
  );
  const cache = caches.default;
  const hit = await cache.match(key);
  if (hit) return hit;

  const res = await handler();
  if (res.status === 200) {
    context.waitUntil(cache.put(key, res.clone()));
  }
  return res;
}

// Uniform error mapping for the three endpoints.
export function errorToResponse(e, asJson) {
  const status = e instanceof SupplyError ? e.status : 500;
  const message = String(e && e.message ? e.message : e);
  if (asJson) return jsonResponse({ error: message }, status, false);
  return textResponse(`error: ${message}\n`, status, false);
}
