// GET /reserves?chainId=8453[&symbol=USDT]
//
// Live, block-pinned snapshot of the EXTERNAL-STABLE RESERVES the issuer has
// taken in — the reserve-side twin of /supply/circulating. Answers the top-line
// commercial question "how much USDT / USDC / USDT0 / EURC have we actually
// taken in?" (docs/BANK_COIN_CAPITAL_STATUS.md §Strategy) as a number any third
// party can reproduce from public RPC reads alone:
//
//   reservesHeld[token] = Σ balanceOf(token, holder)
//
// over the issuer-CUSTODY holder set published in /reserves.json (market-maker
// float + deposit Treasury + DiscountBill + cold storage + the 38 auto-convert
// vaults), read at ONE pinned block. Protocol-owned POOL liquidity is NOT
// counted (that is house-seeded market-making capital, not customer inflow — it
// is reported separately by /pools).
//
// MONEY-TRUTH RULE (CLAUDE.md): every figure is a LIVE chain read; on any RPC
// failure we return HTTP 503, never a stale or fabricated 200. Exact balances
// are integer strings; *Formatted fields are derived display values. Successful
// responses are edge-cached for 60 seconds.
//
// Registry of record: /reserves.json — generated by
// scripts/publish_token_assets.sh from .credentials/cpp/contracts.env with the
// external-stable decimals validated on-chain at publish time. This function
// NEVER hardcodes an address; a poisoned/stale holder set can't be introduced
// at the edge.

import {
  encodeAggregate,
  pad32,
  rpcPost,
  formatUnits,
  corsPreflight,
  SupplyError,
} from "../supply/_lib.js";

const CACHE_SECONDS = 60;

const CORS_HEADERS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, OPTIONS",
  "Access-Control-Allow-Headers": "*",
};

const SEL_BALANCE_OF = "0x70a08231"; // balanceOf(address)

function jsonResponse(obj, status = 200, cacheable = status === 200) {
  return new Response(JSON.stringify(obj, null, 2) + "\n", {
    status,
    headers: {
      ...CORS_HEADERS,
      "Content-Type": "application/json; charset=utf-8",
      "Cache-Control": cacheable
        ? `public, max-age=${CACHE_SECONDS}`
        : "no-store",
      ...(status === 503 ? { "Retry-After": "10" } : {}),
    },
  });
}

// Load the static reserve registry from the deployed tree (mirrors
// supply/_lib.loadConfig + pools.loadPools). Missing registry ⇒ 503, never a guess.
export async function loadReserves(context) {
  const url = new URL("/reserves.json", context.request.url);
  const res = await context.env.ASSETS.fetch(new Request(url.toString()));
  if (!res.ok) {
    throw new SupplyError(503, "reserve registry (reserves.json) unavailable");
  }
  return await res.json();
}

// Decode Multicall3.aggregate's (uint256 blockNumber, bytes[] returnData) where
// every inner return is a single uint256 (balanceOf). Identical logic to
// supply/_lib.js decodeAggregateUints (not exported there); replicated here so
// this function shares no mutable state with the /supply feed.
function decodeAggregateUints(hex, expectedCount) {
  const h = hex.replace(/^0x/, "");
  const word = (i) => h.slice(i * 64, (i + 1) * 64);
  if (h.length < 4 * 64) {
    throw new Error(`aggregate return too short: ${hex.slice(0, 66)}`);
  }
  const arrOffset = Number(BigInt("0x" + word(1))) / 32; // words to bytes[] head
  const n = Number(BigInt("0x" + word(arrOffset)));
  if (n !== expectedCount) {
    throw new Error(`aggregate returned ${n} results, expected ${expectedCount}`);
  }
  const values = [];
  for (let i = 0; i < n; i++) {
    const elemOffsetWords = Number(BigInt("0x" + word(arrOffset + 1 + i))) / 32;
    const elemBase = arrOffset + 1 + elemOffsetWords;
    const len = Number(BigInt("0x" + word(elemBase)));
    if (len !== 32) throw new Error(`inner return ${i} length ${len}, expected 32`);
    values.push(BigInt("0x" + word(elemBase + 1)));
  }
  return values;
}

// One eth_call at one pinned block: balanceOf(token, holder) for every
// (token, holder) pair, flattened token-major (token t, holder h → t*H + h).
// A reverting inner call fails the whole aggregate (⇒ 503) — never a zero-fill.
export async function readReservesViaMulticall(rpcUrl, multicall3, tokens, holders) {
  const bnRes = await rpcPost(rpcUrl, {
    jsonrpc: "2.0",
    id: 0,
    method: "eth_blockNumber",
    params: [],
  });
  if (bnRes.error || !bnRes.result) {
    throw new Error(`${rpcUrl} eth_blockNumber: ${JSON.stringify(bnRes.error)}`);
  }
  const blockHex = bnRes.result;

  const calls = [];
  for (const t of tokens) {
    for (const holder of holders) {
      calls.push({ target: t.address, data: SEL_BALANCE_OF + pad32(holder.address) });
    }
  }
  const res = await rpcPost(rpcUrl, {
    jsonrpc: "2.0",
    id: 1,
    method: "eth_call",
    params: [{ to: multicall3, data: encodeAggregate(calls) }, blockHex],
  });
  if (res.error || !res.result) {
    throw new Error(`${rpcUrl} multicall aggregate: ${JSON.stringify(res.error)}`);
  }
  const values = decodeAggregateUints(res.result, calls.length);
  return { blockNumber: Number(BigInt(blockHex)), values, rpcUrl };
}

async function computeReserves(context) {
  const url = new URL(context.request.url);
  const chainId = url.searchParams.get("chainId");
  if (!chainId) throw new SupplyError(400, "required query param: chainId");
  if (!/^[0-9]+$/.test(chainId)) {
    throw new SupplyError(400, "chainId must be a decimal integer");
  }

  const config = await loadReserves(context);
  const chain = config.chains && config.chains[chainId];
  if (!chain) {
    const chains = Object.keys(config.chains || {});
    throw new SupplyError(
      404,
      `no reserve registry for chainId ${chainId}; supported: ${chains.join(", ")}`
    );
  }

  let tokens = chain.externalStables || [];
  const symbolParam = url.searchParams.get("symbol");
  if (symbolParam) {
    const wanted = symbolParam.toLowerCase();
    tokens = tokens.filter((t) => t.symbol.toLowerCase() === wanted);
    if (!tokens.length) {
      throw new SupplyError(
        404,
        `no external stable '${symbolParam}' on chainId ${chainId}`
      );
    }
  }
  const holders = chain.holders || [];
  const rpcs = chain.rpcs || [];
  const multicall3 = chain.multicall3;
  if (!rpcs.length || !multicall3) {
    throw new SupplyError(
      503,
      `reserve registry missing RPC/multicall config for chainId ${chainId}`
    );
  }
  if (!tokens.length || !holders.length) {
    throw new SupplyError(
      503,
      `reserve registry has no tokens/holders for chainId ${chainId}`
    );
  }

  const H = holders.length;
  const errors = [];
  for (const rpcUrl of rpcs) {
    try {
      const { blockNumber, values } = await readReservesViaMulticall(
        rpcUrl,
        multicall3,
        tokens,
        holders
      );
      const reserves = tokens.map((t, ti) => {
        let total = 0n;
        const perHolder = holders.map((holder, hi) => {
          const bal = values[ti * H + hi];
          total += bal;
          return {
            label: holder.label,
            address: holder.address,
            balance: bal.toString(),
            balanceFormatted: formatUnits(bal, t.decimals),
          };
        });
        return {
          symbol: t.symbol,
          address: t.address,
          decimals: t.decimals,
          totalHeld: total.toString(),
          totalHeldFormatted: formatUnits(total, t.decimals),
          holders: perHolder,
        };
      });
      return {
        chainId: Number(chainId),
        name: chain.name,
        asOfBlock: blockNumber,
        reserves,
        policy: config.policy || {},
        source: {
          rpc: rpcUrl,
          registry: "/reserves.json",
          registryVersion: config.version,
          registryGeneratedAtUtc: config.generatedAtUtc,
        },
      };
    } catch (e) {
      errors.push(String(e && e.message ? e.message : e));
    }
  }
  throw new SupplyError(
    503,
    `all RPC endpoints failed for chainId ${chainId}: ${errors.join(" | ")}`
  );
}

// 60s edge cache (Cache API). Only 200s are cached; errors are never cached.
async function withEdgeCache(context, handler) {
  const url = new URL(context.request.url);
  const key = new Request(
    `${url.origin}${url.pathname}?chainId=${
      url.searchParams.get("chainId") || ""
    }&symbol=${(url.searchParams.get("symbol") || "").toLowerCase()}`,
    { method: "GET" }
  );
  const cache = caches.default;
  const hit = await cache.match(key);
  if (hit) return hit;
  const res = await handler();
  if (res.status === 200) context.waitUntil(cache.put(key, res.clone()));
  return res;
}

export async function onRequestGet(context) {
  return withEdgeCache(context, async () => {
    try {
      return jsonResponse(await computeReserves(context));
    } catch (e) {
      const status = e instanceof SupplyError ? e.status : 500;
      return jsonResponse(
        { error: String(e && e.message ? e.message : e) },
        status,
        false
      );
    }
  });
}

export function onRequestOptions() {
  return corsPreflight();
}

// HEAD behaves like GET minus the body (the runtime strips it).
export { onRequestGet as onRequestHead };
