// GET /anchor-flow?chainId=8453[&blocks=1800]
//
// REAL external-stable inflow monitor. Decodes every Uniswap-v3 Swap at the
// kUSD anchor pools (kUSD/USDC + kUSD/USDT, core 0.01% + wall 0.05%) over a
// recent block window, so ops can see whether people are actually BUYING kUSD
// with real USDC/USDT — the only metric that matters. (As of 2026-07-08 only
// ~$118 of real external stables had ever flowed in against ~$20M of standing
// kUSD anchor depth; this endpoint measures that flow directly.)
//
// MONEY-TRUTH RULE (CLAUDE.md): every figure is a LIVE chain read. On any RPC
// failure across ALL configured endpoints we return HTTP 503 — never a partial
// window served as complete, never stale-as-fresh (same discipline as /pools
// and /supply/*). Signed amounts are exact int256 values carried as strings;
// the formatted decimals are DERIVED display values computed at the leaf.
// Window caps NEVER silently truncate: if a caller asks for more than the hard
// cap we serve the capped window AND flag windowCapped:true with a note.
//
// Pool universe: /pools.json — the static registry generated by
// scripts/publish_token_assets.sh (live factory.getPool over the anchor pairs).
// We keep only the kUSD/{USDC,USDT,USDT0} anchor pools for the chain; this
// function NEVER resolves pools itself (a poisoned/stale list can't enter at
// the edge). Block timestamps are best-effort: a missing timestamp yields
// timestamp:null on that swap, it does NOT 503 the whole feed.

import {
  rpcPost,
  formatUnits,
  corsPreflight,
  SupplyError,
} from "../supply/_lib.js";

const CACHE_SECONDS = 30;

// keccak256("Swap(address,address,int256,int256,uint160,uint128,int24)")
const SWAP_TOPIC0 =
  "0xc42079f94a6350d7e6235f29174924f928cc2ac818eb64fed8004e115fbcca67";

// External stables kUSD anchors against (USD-referenced legs we count as "in").
const ANCHOR_STABLES = new Set(["USDC", "USDT", "USDT0"]);

// Window defaults: ~1h on Base's ~2s blocks. Hard cap keeps getLogs work and
// timestamp fan-out bounded (10 × 500-block chunks) and inside public-RPC
// limits. Exceeding the cap is served capped + flagged, never silently cut.
const DEFAULT_BLOCKS = 1800;
const MAX_BLOCKS = 5000;
// getLogs chunk size. Base's public RPC caps a single getLogs at a 10,000-block
// RANGE (error -32614) but RATE-LIMITS many sequential requests (429 from the
// Cloudflare edge — verified 2026-07-08: 10×500-block chunks tripped 429 while
// 1 large chunk succeeds). So we chunk to the largest window that stays under
// the range cap: the whole ≤5000-block window becomes ONE getLogs call, and the
// chunk loop still bounds work correctly if MAX_BLOCKS is ever raised past 10k.
const GETLOGS_CHUNK = 9000;
const MAX_BATCH_CALLS = 10; // public RPC JSON-RPC batch cap (see _lib.js)

const CORS_HEADERS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, OPTIONS",
  "Access-Control-Allow-Headers": "*",
};

function jsonResponse(obj, status = 200, cacheable = status === 200) {
  return new Response(JSON.stringify(obj, null, 2) + "\n", {
    status,
    headers: {
      ...CORS_HEADERS,
      "Content-Type": "application/json; charset=utf-8",
      "Cache-Control": cacheable
        ? `public, max-age=${CACHE_SECONDS}`
        : "no-store",
      ...(status === 503 ? { "Retry-After": "10" } : {}),
    },
  });
}

// ---------------------------------------------------------------------------
// Decoders (pure — exported so a Node verification harness can replay them
// against real on-chain logs, the AUDITOR view of the three-way reconcile).
// ---------------------------------------------------------------------------

const TWO_255 = 1n << 255n;
const TWO_256 = 1n << 256n;

// Two's-complement int256 from a 64-hex word (no 0x). Uniswap v3 encodes
// amount0/amount1 as SIGNED: positive = token flowed INTO the pool, negative =
// out. This is the load-bearing decode for BUY vs SELL direction.
export function decodeInt256(word64) {
  const v = BigInt("0x" + word64);
  return v >= TWO_255 ? v - TWO_256 : v;
}

// int24 tick decoder (identical to /pools): the ABI sign-extends int24 to the
// full 32-byte word, so a naive full-word signed read yields a value OUTSIDE
// int24 range. Read the low 24 bits and sign-extend from bit 23 — correct
// regardless of upstream padding. e.g. word …fffff9d ⇒ 0xffff9d ⇒ −99.
export function decodeInt24(word64) {
  const low24 = BigInt("0x" + word64.slice(-6));
  return low24 >= 0x800000n ? low24 - 0x1000000n : low24;
}

function topicToAddress(topic) {
  return ("0x" + topic.slice(-40)).toLowerCase();
}

// Decode one Swap log against its anchor-pool descriptor. Returns the fully
// resolved swap record (raw signed strings + derived formatted decimals).
export function decodeSwap(log, pool) {
  const data = (log.data || "").replace(/^0x/, "");
  if (data.length < 5 * 64) {
    throw new Error(
      `Swap data too short for ${pool.pair} (${pool.pool}) tx ${log.transactionHash}`
    );
  }
  const word = (i) => data.slice(i * 64, (i + 1) * 64);
  const amount0 = decodeInt256(word(0)); // token0 delta (signed)
  const amount1 = decodeInt256(word(1)); // token1 delta (signed)
  const tick = decodeInt24(word(4));

  // token0/token1 by lexicographic address order (token0 = smaller lowercased
  // hex). amount0↔token0, amount1↔token1.
  const kusdIsToken0 = pool.kusdAddr < pool.stableAddr;
  const stableAmount = kusdIsToken0 ? amount1 : amount0;
  const kusdAmount = kusdIsToken0 ? amount0 : amount1;

  // Sign convention: stableAmount > 0 ⇒ stable flowed INTO the pool ⇒ someone
  // BOUGHT kUSD with real external stable (the inflow we want). < 0 ⇒ stable
  // left our reserves (kUSD sold back).
  const direction = stableAmount > 0n ? "BUY_kUSD" : "SELL_kUSD";

  return {
    block: Number(BigInt(log.blockNumber)),
    timestamp: null, // filled in later (best-effort)
    tx: log.transactionHash,
    logIndex: Number(BigInt(log.logIndex)),
    pool: pool.pool,
    pair: pool.pair,
    fee: pool.fee,
    direction,
    stableSymbol: pool.stableSymbol,
    stableAmount: formatUnits(stableAmount, pool.stableDecimals),
    stableAmountRaw: stableAmount.toString(),
    kusdAmount: formatUnits(kusdAmount, pool.kusdDecimals),
    kusdAmountRaw: kusdAmount.toString(),
    sender: topicToAddress(log.topics[1]),
    recipient: topicToAddress(log.topics[2]),
    tick: Number(tick),
    // internal (stripped from response): exact signed stable delta for summing
    _stableRaw: stableAmount,
  };
}

// ---------------------------------------------------------------------------
// Registry
// ---------------------------------------------------------------------------

async function loadPools(context) {
  const url = new URL("/pools.json", context.request.url);
  const res = await context.env.ASSETS.fetch(new Request(url.toString()));
  if (!res.ok) throw new SupplyError(503, "pool registry (pools.json) unavailable");
  return await res.json();
}

// Normalise a registry row into an anchor descriptor with kUSD/stable roles
// resolved (defensive to either symbol ordering in the registry).
function toAnchor(row) {
  let kusdSym, kusdAddr, kusdDecimals, stableSym, stableAddr, stableDecimals;
  if (row.symA === "kUSD") {
    kusdSym = row.symA; kusdAddr = row.addrA; kusdDecimals = row.decimalsA;
    stableSym = row.symB; stableAddr = row.addrB; stableDecimals = row.decimalsB;
  } else {
    kusdSym = row.symB; kusdAddr = row.addrB; kusdDecimals = row.decimalsB;
    stableSym = row.symA; stableAddr = row.addrA; stableDecimals = row.decimalsA;
  }
  return {
    pair: row.pair,
    fee: row.fee,
    pool: row.pool,
    kusdSym,
    kusdAddr: kusdAddr.toLowerCase(),
    kusdDecimals,
    stableSymbol: stableSym,
    stableAddr: stableAddr.toLowerCase(),
    stableDecimals,
  };
}

// ---------------------------------------------------------------------------
// Chain reads (one RPC endpoint, whole window; caller fails over on throw)
// ---------------------------------------------------------------------------

async function latestBlock(rpcUrl) {
  const r = await rpcPost(rpcUrl, {
    jsonrpc: "2.0", id: 0, method: "eth_blockNumber", params: [],
  });
  if (r.error || !r.result) {
    throw new Error(`${rpcUrl} eth_blockNumber: ${JSON.stringify(r.error)}`);
  }
  return Number(BigInt(r.result));
}

// getLogs for the Swap topic across all anchor pool addresses, chunked to
// GETLOGS_CHUNK-block windows and aggregated. A chunk error throws (⇒ fail
// over to the next RPC ⇒ 503 if all fail) — never a partial window.
async function getSwapLogs(rpcUrl, poolAddrs, fromBlock, toBlock) {
  const logs = [];
  for (let start = fromBlock; start <= toBlock; start += GETLOGS_CHUNK) {
    const end = Math.min(start + GETLOGS_CHUNK - 1, toBlock);
    const r = await rpcPost(rpcUrl, {
      jsonrpc: "2.0", id: 1, method: "eth_getLogs",
      params: [{
        fromBlock: "0x" + start.toString(16),
        toBlock: "0x" + end.toString(16),
        address: poolAddrs,
        topics: [SWAP_TOPIC0],
      }],
    });
    if (r.error) {
      throw new Error(
        `${rpcUrl} eth_getLogs [${start},${end}]: ${JSON.stringify(r.error)}`
      );
    }
    if (!Array.isArray(r.result)) {
      throw new Error(
        `${rpcUrl} eth_getLogs [${start},${end}]: non-array result`
      );
    }
    logs.push(...r.result);
  }
  return logs;
}

// Best-effort block timestamps: dedupe the block numbers we actually have and
// batch eth_getBlockByNumber. On ANY failure we return an empty map (caller
// leaves timestamp:null) — a missing timestamp must never 503 the flow feed.
async function resolveTimestamps(rpcUrl, blockNums) {
  const out = new Map();
  const unique = [...new Set(blockNums)];
  try {
    for (let i = 0; i < unique.length; i += MAX_BATCH_CALLS) {
      const chunk = unique.slice(i, i + MAX_BATCH_CALLS);
      const batch = chunk.map((bn, j) => ({
        jsonrpc: "2.0", id: j,
        method: "eth_getBlockByNumber",
        params: ["0x" + bn.toString(16), false],
      }));
      const res = await rpcPost(rpcUrl, batch);
      if (!Array.isArray(res)) return new Map(); // shape mismatch ⇒ give up quietly
      for (let j = 0; j < res.length; j++) {
        const blk = res[j] && res[j].result;
        if (blk && blk.timestamp) out.set(chunk[j], Number(BigInt(blk.timestamp)));
      }
    }
  } catch {
    return new Map();
  }
  return out;
}

// ---------------------------------------------------------------------------
// Summary (signed BigInt sums — no floats, per CLAUDE.md)
// ---------------------------------------------------------------------------

function buildSummary(anchors, swaps) {
  // Per-pool tallies (every anchor pool listed, even with zero swaps, so ops
  // sees full coverage).
  const perPoolMap = new Map();
  for (const a of anchors) {
    perPoolMap.set(a.pool.toLowerCase(), {
      pool: a.pool, pair: a.pair, fee: a.fee, stableSymbol: a.stableSymbol,
      buys: 0, sells: 0, swaps: 0, _net: 0n, _dec: a.stableDecimals,
    });
  }
  const bySymbol = new Map(); // stableSymbol → signed BigInt sum
  for (const s of swaps) {
    const pp = perPoolMap.get(s.pool.toLowerCase());
    if (pp) {
      pp.swaps += 1;
      if (s.direction === "BUY_kUSD") pp.buys += 1; else pp.sells += 1;
      pp._net += s._stableRaw;
    }
    bySymbol.set(
      s.stableSymbol,
      (bySymbol.get(s.stableSymbol) || 0n) + s._stableRaw
    );
  }

  const perPool = [...perPoolMap.values()].map((p) => ({
    pool: p.pool, pair: p.pair, fee: p.fee, stableSymbol: p.stableSymbol,
    buys: p.buys, sells: p.sells, swaps: p.swaps,
    netStableIn: formatUnits(p._net, p._dec),
    netStableInRaw: p._net.toString(),
  }));

  const usdc = bySymbol.get("USDC") || 0n;
  const usdt = (bySymbol.get("USDT") || 0n) + (bySymbol.get("USDT0") || 0n);
  let total = 0n;
  for (const v of bySymbol.values()) total += v; // all anchor legs are 6-dec USD stables
  const netStableInBySymbol = {};
  for (const [sym, v] of bySymbol.entries()) {
    netStableInBySymbol[sym] = { formatted: formatUnits(v, 6), raw: v.toString() };
  }

  return {
    perPool,
    netStableInUSDC: formatUnits(usdc, 6),
    netStableInUSDCRaw: usdc.toString(),
    netStableInUSDT: formatUnits(usdt, 6),
    netStableInUSDTRaw: usdt.toString(),
    netStableInTotal: formatUnits(total, 6),
    netStableInTotalRaw: total.toString(),
    netStableInBySymbol,
  };
}

// ---------------------------------------------------------------------------
// Handler core
// ---------------------------------------------------------------------------

async function computeAnchorFlow(context) {
  const url = new URL(context.request.url);
  const chainId = url.searchParams.get("chainId");
  if (!chainId) throw new SupplyError(400, "required query param: chainId");
  if (!/^[0-9]+$/.test(chainId)) {
    throw new SupplyError(400, "chainId must be a decimal integer");
  }

  // Window: default 1800, hard cap MAX_BLOCKS, NEVER silently truncated.
  const blocksParam = url.searchParams.get("blocks");
  let requestedBlocks = DEFAULT_BLOCKS;
  if (blocksParam !== null) {
    if (!/^[0-9]+$/.test(blocksParam) || blocksParam === "0") {
      throw new SupplyError(400, "blocks must be a positive decimal integer");
    }
    requestedBlocks = Number(blocksParam);
  }
  let windowBlocks = requestedBlocks;
  let windowCapped = false;
  let note;
  if (requestedBlocks > MAX_BLOCKS) {
    windowBlocks = MAX_BLOCKS;
    windowCapped = true;
    note =
      `requested blocks=${requestedBlocks} exceeds hard cap ${MAX_BLOCKS}; ` +
      `serving the most recent ${MAX_BLOCKS} blocks only (window NOT silently ` +
      `truncated — see windowCapped). Query a narrower range or page backwards.`;
  }

  const config = await loadPools(context);
  const registry = config[chainId];
  if (!Array.isArray(registry)) {
    const chains = Object.keys(config).filter((k) => /^[0-9]+$/.test(k));
    throw new SupplyError(
      404,
      `no pool registry for chainId ${chainId}; supported: ${chains.join(", ")}`
    );
  }
  const rpcs = (config.rpcs && config.rpcs[chainId]) || [];
  if (!rpcs.length) {
    throw new SupplyError(503, `pool registry missing RPC config for chainId ${chainId}`);
  }

  // Keep only kUSD/{USDC,USDT,USDT0} anchor pools.
  const anchors = registry
    .filter(
      (r) =>
        (r.symA === "kUSD" && ANCHOR_STABLES.has(r.symB)) ||
        (r.symB === "kUSD" && ANCHOR_STABLES.has(r.symA))
    )
    .map(toAnchor);

  const poolAddrs = anchors.map((a) => a.pool);
  const anchorPoolMap = new Map(anchors.map((a) => [a.pool.toLowerCase(), a]));

  const errors = [];
  for (const rpcUrl of rpcs) {
    try {
      const latest = await latestBlock(rpcUrl);
      const toBlock = latest;
      const fromBlock = Math.max(0, toBlock - windowBlocks);

      // No anchor pools on this chain (e.g. Arbitrum today): honest empty feed,
      // still block-pinned, with a note. Not an error.
      if (!poolAddrs.length) {
        return {
          chainId: Number(chainId),
          fromBlock, toBlock, windowBlocks, windowCapped,
          ...(note ? { note } : {}),
          anchorNote: `no kUSD anchor pools registered for chainId ${chainId}`,
          count: 0, swaps: [],
          summary: {
            perPool: [], netStableInUSDC: "0", netStableInUSDCRaw: "0",
            netStableInUSDT: "0", netStableInUSDTRaw: "0",
            netStableInTotal: "0", netStableInTotalRaw: "0",
            netStableInBySymbol: {},
          },
          source: { rpc: rpcUrl, registry: "/pools.json", registryVersion: config.version },
        };
      }

      const rawLogs = await getSwapLogs(rpcUrl, poolAddrs, fromBlock, toBlock);

      const swaps = [];
      for (const log of rawLogs) {
        const anchor = anchorPoolMap.get((log.address || "").toLowerCase());
        if (!anchor) continue; // not one of ours (defensive)
        swaps.push(decodeSwap(log, anchor));
      }
      // Deterministic order: block asc, then logIndex asc.
      swaps.sort((a, b) => a.block - b.block || a.logIndex - b.logIndex);

      // Best-effort timestamps (never 503s the feed).
      const tsMap = await resolveTimestamps(rpcUrl, swaps.map((s) => s.block));
      for (const s of swaps) {
        if (tsMap.has(s.block)) s.timestamp = tsMap.get(s.block);
      }

      const summary = buildSummary(anchors, swaps);

      // Strip the internal BigInt field before serialising.
      const cleanSwaps = swaps.map(({ _stableRaw, ...rest }) => rest);

      return {
        chainId: Number(chainId),
        fromBlock, toBlock, windowBlocks, windowCapped,
        ...(note ? { note } : {}),
        count: cleanSwaps.length,
        swaps: cleanSwaps,
        summary,
        source: {
          rpc: rpcUrl,
          registry: "/pools.json",
          registryVersion: config.version,
          registryGeneratedAtUtc: config.generatedAtUtc,
          swapTopic0: SWAP_TOPIC0,
          note:
            "stableAmount>0 ⇒ BUY_kUSD (real external stable in); <0 ⇒ SELL_kUSD. " +
            "Amounts are exact int256 (raw) with derived 6-decimal display.",
        },
      };
    } catch (e) {
      errors.push(String(e && e.message ? e.message : e));
    }
  }
  throw new SupplyError(
    503,
    `all RPC endpoints failed for chainId ${chainId}: ${errors.join(" | ")}`
  );
}

// 30s edge cache (Cache API). Only 200s cached; errors never cached.
async function withEdgeCache(context, handler) {
  const url = new URL(context.request.url);
  const key = new Request(
    `${url.origin}${url.pathname}?chainId=${
      url.searchParams.get("chainId") || ""
    }&blocks=${url.searchParams.get("blocks") || ""}`,
    { method: "GET" }
  );
  const cache = caches.default;
  const hit = await cache.match(key);
  if (hit) return hit;
  const res = await handler();
  if (res.status === 200) context.waitUntil(cache.put(key, res.clone()));
  return res;
}

export async function onRequestGet(context) {
  return withEdgeCache(context, async () => {
    try {
      return jsonResponse(await computeAnchorFlow(context));
    } catch (e) {
      const status = e instanceof SupplyError ? e.status : 500;
      return jsonResponse(
        { error: String(e && e.message ? e.message : e) },
        status,
        false
      );
    }
  });
}

export function onRequestOptions() {
  return corsPreflight();
}

// HEAD behaves like GET minus the body (the runtime strips it).
export { onRequestGet as onRequestHead };
