// GET /pools?chainId=8453[&pair=kEUR/kUSD]
//
// Programmatic, block-pinned live snapshot of EVERY kStable Uniswap-v3 pool on
// a chain: current price, tick, off-par %, both token reserves and the pool's
// active liquidity. Built for machine consumption (monitors, keepers, dashboards)
// — the CLI equivalent is scripts/kstable_pools.sh --json.
//
// MONEY-TRUTH RULE (CLAUDE.md): every figure is a LIVE chain read pinned to ONE
// block — all pools in a response share a single consistent state root (one
// Multicall3.aggregate eth_call). On any RPC failure we return HTTP 503, never a
// partial set and never stale-as-fresh (same discipline as /supply/*). Exact
// values (sqrtPriceX96, tick, reserves, liquidity) are returned as integer
// strings; `price`/`offParPct` are DERIVED display floats computed at the leaf.
// Successful responses are edge-cached for 30 seconds.
//
// Pool universe: /pools.json — the static registry generated by
// scripts/publish_token_assets.sh via live factory.getPool() over the seeder
// pair universe + kUSD/{USDC,USDT,USDT0,EURC} anchors at every fee tier. This
// function NEVER resolves pools itself; it reads live state for the registry's
// addresses only (a poisoned/stale pool list can never be introduced at the edge).

import {
  encodeAggregate,
  pad32,
  rpcPost,
  formatUnits,
  corsPreflight,
  SupplyError,
} from "../supply/_lib.js";

const CACHE_SECONDS = 30;

const CORS_HEADERS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, OPTIONS",
  "Access-Control-Allow-Headers": "*",
};

// Uniswap v3 pool + ERC20 selectors.
const SEL_SLOT0 = "0x3850c7bd"; // slot0() -> (uint160,int24,uint16,uint16,uint16,uint8,bool)
const SEL_LIQUIDITY = "0x1a686502"; // liquidity() -> uint128
const SEL_BALANCE_OF = "0x70a08231"; // balanceOf(address) -> uint256

const Q96 = 2n ** 96n;
// Exported: /defillama/yields reuses the exact same block-pinned multicall path
// (readPoolsViaMulticall + buildPool) so the two surfaces can never diverge.
export const CALLS_PER_POOL = 4; // slot0, liquidity, balanceOf(tokenA→pool), balanceOf(tokenB→pool)

function jsonResponse(obj, status = 200, cacheable = status === 200) {
  return new Response(JSON.stringify(obj, null, 2) + "\n", {
    status,
    headers: {
      ...CORS_HEADERS,
      "Content-Type": "application/json; charset=utf-8",
      "Cache-Control": cacheable
        ? `public, max-age=${CACHE_SECONDS}`
        : "no-store",
      ...(status === 503 ? { "Retry-After": "10" } : {}),
    },
  });
}

// Load the static pool registry from the deployed tree (mirrors _lib.loadConfig,
// which loads /supply/exclusions.json). Missing registry ⇒ 503, never a guess.
export async function loadPools(context) {
  const url = new URL("/pools.json", context.request.url);
  const res = await context.env.ASSETS.fetch(new Request(url.toString()));
  if (!res.ok) {
    throw new SupplyError(503, "pool registry (pools.json) unavailable");
  }
  return await res.json();
}

// int24 tick decoder. The ABI already sign-extends int24 to a full 32-byte word,
// but we defensively read the low 24 bits and sign-extend from bit 23 so the
// value is correct regardless of upstream padding: e.g. tick -1280 arrives as
// 0x…fffb00; 0xfffb00 >= 0x800000 ⇒ 0xfffb00 − 0x1000000 = −1280.
function decodeInt24(word64) {
  const low24 = BigInt("0x" + word64.slice(-6));
  return low24 >= 0x800000n ? low24 - 0x1000000n : low24;
}

// Decode Multicall3.aggregate's (uint256 blockNumber, bytes[] returnData) into
// the raw hex (no 0x prefix) of EACH inner call's return. slot0() returns a
// 7-value / 224-byte blob, so a per-uint decoder won't do — we hand back the raw
// bytes and slice the words we need (this is the decodeAggregateUints sibling in
// _lib.js, generalised to variable-length returns).
function decodeAggregateBytes(hex, expectedCount) {
  const h = hex.replace(/^0x/, "");
  const word = (i) => h.slice(i * 64, (i + 1) * 64);
  if (h.length < 4 * 64) {
    throw new Error(`aggregate return too short: ${hex.slice(0, 66)}`);
  }
  const arrOffset = Number(BigInt("0x" + word(1))) / 32; // words to bytes[] head
  const n = Number(BigInt("0x" + word(arrOffset)));
  if (n !== expectedCount) {
    throw new Error(`aggregate returned ${n} results, expected ${expectedCount}`);
  }
  const out = [];
  for (let i = 0; i < n; i++) {
    const elemOffsetWords = Number(BigInt("0x" + word(arrOffset + 1 + i))) / 32;
    const elemBase = arrOffset + 1 + elemOffsetWords;
    const len = Number(BigInt("0x" + word(elemBase))); // bytes length
    const start = (elemBase + 1) * 64;
    out.push(h.slice(start, start + len * 2));
  }
  return out;
}

// One eth_call at one pinned block: slot0 + liquidity + both pool reserves for
// every pool. Reverting inner calls fail the whole aggregate (⇒ 503) — never a
// zero-filled pool.
export async function readPoolsViaMulticall(rpcUrl, multicall3, pools) {
  const bnRes = await rpcPost(rpcUrl, {
    jsonrpc: "2.0",
    id: 0,
    method: "eth_blockNumber",
    params: [],
  });
  if (bnRes.error || !bnRes.result) {
    throw new Error(`${rpcUrl} eth_blockNumber: ${JSON.stringify(bnRes.error)}`);
  }
  const blockHex = bnRes.result;

  const calls = [];
  for (const p of pools) {
    calls.push({ target: p.pool, data: SEL_SLOT0 });
    calls.push({ target: p.pool, data: SEL_LIQUIDITY });
    calls.push({ target: p.addrA, data: SEL_BALANCE_OF + pad32(p.pool) });
    calls.push({ target: p.addrB, data: SEL_BALANCE_OF + pad32(p.pool) });
  }

  const res = await rpcPost(rpcUrl, {
    jsonrpc: "2.0",
    id: 1,
    method: "eth_call",
    params: [{ to: multicall3, data: encodeAggregate(calls) }, blockHex],
  });
  if (res.error || !res.result) {
    throw new Error(`${rpcUrl} multicall aggregate: ${JSON.stringify(res.error)}`);
  }
  const raw = decodeAggregateBytes(res.result, calls.length);
  return { blockNumber: Number(BigInt(blockHex)), raw, rpcUrl };
}

// Assemble one pool's public record from its 4 raw returns (base = 4*index).
export function buildPool(p, raw, base) {
  const slot0 = raw[base + 0];
  const liqRaw = raw[base + 1];
  const balARaw = raw[base + 2];
  const balBRaw = raw[base + 3];
  if (!slot0 || slot0.length < 128) {
    throw new Error(`slot0 malformed for ${p.pair} (${p.pool})`);
  }
  const sqrtPriceX96 = BigInt("0x" + slot0.slice(0, 64)); // word0: uint160
  const tick = decodeInt24(slot0.slice(64, 128)); // word1: int24
  const liquidity = BigInt("0x" + (liqRaw || "0"));
  const reserveARaw = BigInt("0x" + (balARaw || "0"));
  const reserveBRaw = BigInt("0x" + (balBRaw || "0"));

  // price = (sqrtPriceX96 / 2^96)^2 = token1 per token0 (both legs 6-dec, so the
  // raw ratio equals the whole-unit ratio). Derived display float — the exact
  // truth is sqrtPriceX96 / tick above, returned as strings.
  const sp = Number(sqrtPriceX96) / Number(Q96);
  const price = sp * sp;
  const offParPct = (Math.pow(1.0001, Number(tick)) - 1) * 100;

  return {
    pair: p.pair,
    symA: p.symA,
    symB: p.symB,
    fee: p.fee,
    pool: p.pool,
    addrA: p.addrA,
    addrB: p.addrB,
    tick: Number(tick),
    sqrtPriceX96: sqrtPriceX96.toString(),
    price,
    offParPct,
    reserveA: formatUnits(reserveARaw, p.decimalsA),
    reserveB: formatUnits(reserveBRaw, p.decimalsB),
    reserveARaw: reserveARaw.toString(),
    reserveBRaw: reserveBRaw.toString(),
    liquidity: liquidity.toString(),
  };
}

async function computePools(context) {
  const url = new URL(context.request.url);
  const chainId = url.searchParams.get("chainId");
  const pairParam = url.searchParams.get("pair");
  if (!chainId) throw new SupplyError(400, "required query param: chainId");
  if (!/^[0-9]+$/.test(chainId)) {
    throw new SupplyError(400, "chainId must be a decimal integer");
  }

  const config = await loadPools(context);
  const registry = config[chainId];
  if (!Array.isArray(registry)) {
    const chains = Object.keys(config).filter((k) => /^[0-9]+$/.test(k));
    throw new SupplyError(
      404,
      `no pool registry for chainId ${chainId}; supported: ${chains.join(", ")}`
    );
  }
  const rpcs = (config.rpcs && config.rpcs[chainId]) || [];
  const multicall3 = config.multicall3;
  if (!rpcs.length || !multicall3) {
    throw new SupplyError(
      503,
      `pool registry missing RPC/multicall config for chainId ${chainId}`
    );
  }

  let pools = registry;
  if (pairParam) {
    const wanted = pairParam.toLowerCase();
    pools = registry.filter((p) => p.pair.toLowerCase() === wanted);
    if (!pools.length) {
      throw new SupplyError(
        404,
        `no pool matching pair '${pairParam}' on chainId ${chainId}`
      );
    }
  }

  const errors = [];
  for (const rpcUrl of rpcs) {
    try {
      const { blockNumber, raw } = await readPoolsViaMulticall(
        rpcUrl,
        multicall3,
        pools
      );
      const out = pools.map((p, i) => buildPool(p, raw, i * CALLS_PER_POOL));
      return {
        chainId: Number(chainId),
        asOfBlock: blockNumber,
        count: out.length,
        pools: out,
        source: {
          rpc: rpcUrl,
          registry: "/pools.json",
          registryVersion: config.version,
          registryGeneratedAtUtc: config.generatedAtUtc,
        },
      };
    } catch (e) {
      errors.push(String(e && e.message ? e.message : e));
    }
  }
  throw new SupplyError(
    503,
    `all RPC endpoints failed for chainId ${chainId}: ${errors.join(" | ")}`
  );
}

// 30s edge cache (Cache API). Only 200s are cached; errors are never cached.
async function withEdgeCache(context, handler) {
  const url = new URL(context.request.url);
  const key = new Request(
    `${url.origin}${url.pathname}?chainId=${
      url.searchParams.get("chainId") || ""
    }&pair=${(url.searchParams.get("pair") || "").toLowerCase()}`,
    { method: "GET" }
  );
  const cache = caches.default;
  const hit = await cache.match(key);
  if (hit) return hit;
  const res = await handler();
  if (res.status === 200) context.waitUntil(cache.put(key, res.clone()));
  return res;
}

export async function onRequestGet(context) {
  return withEdgeCache(context, async () => {
    try {
      return jsonResponse(await computePools(context));
    } catch (e) {
      const status = e instanceof SupplyError ? e.status : 500;
      return jsonResponse(
        { error: String(e && e.message ? e.message : e) },
        status,
        false
      );
    }
  });
}

export function onRequestOptions() {
  return corsPreflight();
}

// HEAD behaves like GET minus the body (the runtime strips it).
export { onRequestGet as onRequestHead };
